hallway_list = [ # TOTAL- 54
    ["You enter a tunnel with a slightly downward slope."],
    ["You enter a tunnel with a slightly upward slope."],
    ["You enter a tunnel with a little stream of water flowing down it's slope."],
    ["You enter a tunnel with a colony of colorful mushrooms growing along its edges."],
    ["You find yourself in a tunnel with a colony of bioluminescent mushrooms illuminating a path through."],
    ["You come across a tunnel with moss growing on its walls.",  "The air is damp and has a slight stink."],
    ["You find yourself in a tunnel with large, uneven cracks in the stone floor."],
    ["You come across a tunnel that smells sweet somehow?"],
    ["You enter a tunnel that looks like it was well travelled at one point."],
    ["You find yourself in a tunnel with tiny glowing crystals clustered along its edges."],
    ["You come across a rocky tunnel with large ridges along its ceiling.",  "It feels like you're walking down a massive rib cage."],
    ["You find yourself in a cavern with a little creek to wander aside.", "The gentle trickling sounds are a welcoming comfort."],
    ["While wandering a rocky cavern, you hear the sourceless sounds of a babbling brook.", "You realize the stream runs beneath the rocks here."],
    ["You come across a hallway built of rough, stone bricks."],
    ["You start to notice a mild stench of mildew while traversing a tunnel.", "It's bearable but gross."],
    ["You enter a hallway built of smooth, stone bricks."],
    ["You enter a hallway glowing from refracted light bouncing of a water's surface.","You're not sure where the water is or the light sourced, but it's very beautiful."],
    ["You enter a hallway built of massive glass bricks. They seem impractical."],
    ["You find yourself in a hallway built of smooth, black bricks.",  "Halfway down there's a glass walkway, a window to a lake of lava hundreds of feet below you."],
    ["A wave of intense heat hits you as you come across a massive lake of flowing lava.",  "A pathway of rock traverses the length of it."],
    ["A wave of intense heat hits you as you come across a massive lake of flowing lava.", "A trail of rocks would serve as a jumping path to cross it."],
    ["You find yourself crossing a stone bridge that drops into an empty expanse on both sides."],
    ["You find yourself crossing a stone bridge that drops into a rapid river a hundred feet below."],
    ["You find yourself crossing a wooden bridge. Below you see a forest canopy hundreds of feet down."],
    ["The path opens up to a drop on one side. The path is wide enough, but it'd be best to hug the wall."],
    ["After a stretch, the tunnel you're in has shrunk till you're crawling to get through.", "Finally, you reach a point where it opens again, and you can continue onward."],
    ["After a stretch, the tunnel you're in has shrunk till you're ducking to get through.",  "Fortunately, you reach a point where it opens again, and you can continue onward."],
    ["The air turns frigid as you enter a cavern filled with snow and an icy wind."],
    ["The air turns frigid as you enter a cavern filled with snow and an icy breeze.", "You slip on your way in, but catch yourself before falling."],
    ["The air turns cool as you enter a cavern filled with snow.", "You see a pathway where it's been packed down."],
    ["You enter a cavern filled with snow, but strangely it isn't cold."],
    ["Your path travels across a sloped ridge. You notice the pleasant scent of baked goods in the air.", "Is it wishful thinking or something nearby?"],
    ["Your path travels across a sloped ridge. It looks sketchy but probably traversable."],
    ["Your path travels across a sloped ridge. A harsh wind hits your cheeks."],
    ["The tunnel you're traveling through has a sharp, sourceless wind.", "It dries your eyes no matter which direction you're facing."],
    ["The tunnel you're traveling through has a harsh, sourceless wind.", "Luckily it seems to always hit your back, no matter with direction you're facing."],
    ["The path becomes a long, unremarkable, rocky tunnel."],
    ["The path becomes a long, unremarkable, rocky tunnel.", "Your thoughts drift to the idea of fresh pie."],
    ["The path becomes a long, unremarkable, rocky tunnel.", "Your start to miss your friends a little."],
    ["The path becomes a long, unremarkable, rocky tunnel.", "You notice you've been humming for a while now."],
    ["While traveling through a tunnel, you come across a pair of butterflies.",  "A glimmering, blue mist gently cascades from them as they flutter around."],
    ["While traveling through a tunnel, you come across a pair of lizards skittering vertically along the wall."],
    ["While traveling along the edge of a wide chasm, you glimpse a pair of elephants passing on the opposite side."],
    ["While traveling along the edge of a wide chasm, you glimpse another adventurer",  "fighting a skeleton on the opposite side. She seems confident and bests the monster."],
    ["You enter an abandoned mining tunnel. There's not much remaining from that time."],
    ["You enter an abandoned mining tunnel. There's a rundown minecart along a broken track."],
    ["While traveling through a tunnel, a family of ducks passes you by.", "One-by-one they each nod to you as they continue their business."],
    ["You round a corner and see an ethereal, magic aura floating about in the tunnel ahead.", "It seems benign."],
    ["You round a corner and see an ethereal, magic aura floating about in the tunnel ahead.", "It flees after noticing you."],
    ["The tunnel opens up slightly to a small rocky chamber.", "You hear a muffled, sourceless giggling."],
    ["While traveling through a tunnel, you notice a ripple rolling across the ceiling above you.", "Turning upward, it seems you've been passing underneath a body of water.", "Reaching up you brush the water gently, a few dropplets fall loose, but otherwise it's unbothered."],
    ["Your route opens up to a medium-sized chamber.", "You see a strange shadow across the floor, looking up you see a school of fish swimming through the air."],
    ["A long brick hallway with faux windows that look out to more bricks."],
    ["A short hallway of bricks, bound by a metal instead of mortar."],
]

dead_end_list = [ # TOTAL- 31
    ["After a long stretch with no offshoots, you hit a frustrating dead end."],
    ["After a long stretch with no offshoots, you hit another dead end."],
    ["After traveling an eerily straight hallway for nearly 30 minutes,",  "you finally hit a dead end."],
    ["While traveling a long brick hallway, you suddenly find a wall of a different brick blocking your path."],
    ["You find yourself zig-zagging downward for twenty minutes, before hitting a dead end."],
    ["You find yourself traveling downward for several minutes, before hitting a dead end."],
    ["After a stretch the tunnel you're in has shrunk till you're crawling to get through.",  "Finally you reach a point where you can't go further, and have to turn back."],
    ["You see ahead that the path you're traveling suddenly drops downward into an abyss.", "You'd fall to your death if you kept going this way."],
    ["A wave of intense heat hits you as your path leads to a massive lake of flowing lava.",  "You aren't able to find a way to cross it."],
    ["You find yourself crossing a stone bridge that drops into an empty expanse on both sides.", "You notice that the bridge has collapsed ahead and there's no visible other side."],
    ["You find yourself crossing an old, wood bridge that drops into an empty expanse on both sides.", "The creaking intensifies and you're confident it will collapse if you keep going."],
    ["You find yourself crossing a stone bridge that drops into an empty expanse on both sides.", "Suddenly there's a loud explosion of sound a mile above you!!", "A massive rock falls from the ceiling and destroys the bridge in front of you!"],
    ["A rocky tunnel with uneven footing.", "Suddenly the ground starts shaking and several rocks fall from the ceiling!", "As you rapidly back up, the pathway ahead is collapsed."],
    ["You come across a sea of strange flora emmitting a toxic gas.", "After investigating for a moment, there's no way to safely pass through."],
    ["A tunnel that's rising gently. After some time, you find it's collapsed ahead."],
    ["As you're traversing the path, the tunnel you're in has a massive sinkhole that's way too big to cross."],
    ["You hear a raucous sound ahead and the tunnel you're in opens to a large cavern.", "Standing on an outcropping, you have a vantage point and notice the sea of goblins down further.", "There's no way to survive that many, and they haven't noticed you yet. Best to turn back."],
    ["The path leads to a large rapid river. It doesn't seem like there's a viable way across, its just too big."],
    ["After a time you start to notice a hellish stench. You press on but it gets worse and worse.", "Eventually you're confident that whatever lies ahead will the death of you."],
    ["As you travel across a sloped ridge, you notice several glowing green orbs moving amongst the floor ahead.", "You see that a mudslide has blocked the path, and several dozen GOLEMS are amongst it.", "They either haven't noticed you or aren't fully corporeal yet. Best to turn back quickly."],
    ["While traveling through the ruins of an old town, you spot the unmistakable glow of a fire ahead!", "It's spreading, and likely won't leave any safe places to avoid it. Gotta turn back!"],
    ["While traveling an open cavern with a massive uncrossable chasm to your left,",  "you suddenly find you're out of path to explore.",  "You hunt for more routes, but eventually accept it's a dead end."],
    ["Something is off. You've been traveling this dark, brick hallway for close to an hour,", "but it seems to be repeating itself? You walk back 50 or so feet and find yourself at the entrance.", "There's somekind of magic on this place, but it's beyond your grasp so it's a deadend."],
    ["After traveling a hallway for some time, you see a violent magical aura exploding continuously ahead!", "You backpedal a few feet before the magic notices you, these things tend to escalate quickly."],
    ["After a short walk, you find that your path leads to a strange portal.", "Unprepared for interdimensional travel, you'll have to turn back."],
    ["After a short while, you find the path ahead has been blocked by a large, humming machine.", "There's no way around it, and you can't tell what the machine is doing."],
    ["After a short while, you find the path ahead has been blocked by a sleeping triceratops.", "Seems like it's having a nice dream so it'd be a shame to wake it up."],
    ["After a short while, you find the path ahead has been blocked by a gigantic curled up cat.", "You ask it to move, but cats do what they want."],
    ["After a short while, you find the path ahead has been blocked by a gigantic tortoise.", "After asking nicely, it's willing to move for you but it'd take too long anyway."],
    ["Your path opens up to a small grassy chamber. There's no exits, but it's kind of peaceful here."],
    ["Your path opens up to a small chamber with large sandbox. There's no exits, and you're a little old for sandboxes.."],
    ["Your route bends a corner, and you come face to face with a massive mechanical construct.", "The creature is stuck on a crawling position and blocks the path onward.", "It holds out a gently closed hand to show it's friendly, there's no telling how long it's been stuck here."]
]