hallway_list =     [
        ["A tunnel with a slightly downward slope."],
        ["A tunnel with a slightly upward slope."],
        ["A tunnel with a colony of colorful mushrooms growing along its edges."],
        ["A tunnel with a colony of bioluminescent mushrooms illuminating a path through."],
        ["A tunnel with moss growing on its walls.", 
            "The air is damp and has a slight stink."],
        ["A tunnel with large, uneven cracks in the stone floor."],
        ["A tunnel that smells sweet somehow?"],
        ["A tunnel that looks like it was well travelled at one point."],
        ["A tunnel with tiny glowing crystals clustered along its edges."],
        ["A rocky tunnel with large ridges along its ceiling.", 
            "It feels like you're walking down a massive rib cage."],
        ["A hallway built of rough, stone bricks."],
        ["A hallway built of smooth, stone bricks."],
        ["A hallway built of massive glass bricks. They seem impractical."],
        ["A hallway built of smooth, black bricks.", 
            "Halfway down there's a glass walkway, a window to a lake of lava hundreds of feet below you."],
        ["A wave of intense heat hits you as you come across a massive lake of flowing lava.", 
            "There's a pathway of rock that traverses the length of it."],
        ["A wave of intense heat hits you as you come across a massive lake of flowing lava.",
            "There's a trail of rocks like little island that you can jump across."],
        ["You find yourself crossing a stone bridge that drops into an empty expanse on both sides."],
        ["You find yourself crossing a stone bridge that drops into a rapid river a hundred feet below."],
        ["You find yourself crossing a wooden bridge. Below you see a forest canopy hundreds of feet down."],
        ["The path opens up to a drop on one side. The path is wide enough, but it'd be best to hug the wall."]
    ]