import random
from classes.dungeon.room_components import Exit, MonsterSpawning
from classes.dungeon.room import Room
from lists.monsters_list import Goblin, Skeleton, Wizard, MudGolem, Minotaur, Avatar, MagmaGoblin, FlyingGoblin
from lists.interactables_list import Owl, Pool, MagicBarrier, LockedDoor, SecretPassage, Mimic, PileOfMoney, SleepingMinotaur, Container,  Artisan, Breakable, Bed, Inspectable, Chasm, RedHerring, GlowingCrystal, ExitHold, Chest, MagmaRiver, MoneyTree, Tree, Cauldron, NPC, ShopOwner, GlowingTree, Fairy
from lists.items_lists import weapon_options, armor_options, misc_options, Pie, HealthPotion, StatMedallion, PowerBerry, DurabilityGem, MagicWand, SmokeBomb, GreaterHealthPotion
from lists.adjustments_list import block_exit, obtain_idol, reveal_mimics, obtain_item, chasm_sea_creature_start1, golem_machinery, add_castle_wave, inspectable_renew, reveal_passage, inspect_control_panel, randomize_container_contents, change_adjustable_argument, ceribane_alchemy, adjustment_print, remove_item, inspect_crystal, inspect_machine, break_the_table, clear_cave_in, add_interactable, add_owl, teleport_sequence, add_to_interactable, money_tree_refresh, change_room_description, change_room, add_monsters, change_monster_spawning, shop_refresh, sea_creature_defeated, tree_inspect_renew, damage_player

room_list = [ 
    [
        Room("ROOMS MAXED", 
            'A deadend with a sign that reads "Sorry, more rooms will be added soon!"', 
            [Exit(0), Exit(1)]) #the second exit needs to be removed when this room is updated (maybe)
        ],
    [
        Room("DUNGEON ENTRANCE", 
            "Here's a short placeholder description about the Dungeon Entrance.", 
            [Exit(0, Room("GO HOME", 
                        "You decide not to explore the dungeon. Probably a good idea.", 
                        None)), Exit(1), Exit(2)]),
        Room("IDOL ROOM",
            "A massive chamber with collumns of ancient stone rising to the massive ceiling. Before you steps lead to an altar where the IDOL OF DYNAE has finally been found! However, a MAGIC BARRIER blocks your way forward.",
            [Exit(0)],
            MonsterSpawning(2, Minotaur),
            [MagicBarrier("IDOL OF DYNAE", obtain_idol),
                RedHerring("PILLARS", stealth_mod=5)],
            [[inspectable_renew], [], {}]),
        Room("POND ROOM", 
            "A room with a small pond.", 
            [Exit(0), Exit(1), Exit(2)], 
            MonsterSpawning(1, Goblin, 5, Skeleton), 
            [Pool(0, "POND", ["SWIM", "THROW ROCKS"], "A naturally formed pool of cave water. It's roughly the size of a small market.")],
            [[add_to_interactable, change_room_description],
                [sea_creature_defeated], 
                {"add_to_interactable" : [2, "INSPECT SHADOW"],
                "change_room_description" : [2, "A room with a small pond... Wait- there's a shadow in the water that wasn't there before."],
                "sea_creature_defeated" : ["A room with a small pond, the corpse of a sea creature is floating in the water."],
                "damage_player" : ["Your armor is too heavy to swim in!", 2]}]),
        Room("LAKE ROOM", 
            "You hear the sound of water lapping against rocks. To your side there's a rocky bank and a large lake. You see a shadow beneath the water about 20 feet out.", 
            [Exit(0), Exit(1), Exit(2)], 
            MonsterSpawning(4, Wizard, 9, "TWICE"), 
            [Pool(0, "LAKE", ["SWIM", "INSPECT SHADOW", "THROW ROCKS"], "A large underground lake, it's edges lost to the darkness.")],
            [[], [sea_creature_defeated], {"damage_player" : ["Your armor is too heavy to swim in!", 2],
                                            "sea_creature_defeated" : ["You hear the sound of water lapping against rocks. To your side there's a rocky bank and a large lake with the corpse of a sea creature floating on the surface."],
                                            }]),
        # Room("SLEEPING MINOTAUR",
        #     "An open chamber with a minotaur sleeping on a fur rug.",
        #     [Exit(0)],
        #     None,
        #     [SleepingMinotaur("It seems fast asleep. Admittedly its a cozy-looking rug"),
        #         Tree(1, ["PICK FRUIT", "CHOP"], " magnolia", 3),
        #         Tree(2, ["PICK FRUIT", "CHOP"], " magnolia", 3),
        #         Tree(3, ["PICK FRUIT", "CHOP"], " magnolia", 3)],
        #     [[], [change_room_description], {"add_monsters" : [0, 1, Minotaur], "change_room_description" : [0, "An open chamber with a minotaur standing alert on a fur rug."]}]),
        # Room("CHASM ROOM",
        #     "A narrow chasm",
        #     [Exit(0)],
        #     MonsterSpawning(7, FlyingGoblin, 10, "TWICE"),
        #     [Chasm(0, ["JUMP", "THROW ROCKS"], ". After a moment you hear it clanking against the hard stone below.", 5)],
        #     [[], [], {"jump_failure" : [" You land abruptly, smashing into the ground below.", 4],
        #                 "change_room" : [Exit(2, Room("CHASM LANDING",
        #                                             "A hard stone landing, its a strange place for a mural to be.",
        #                                             [Exit(0), Exit(1), Exit(2), Exit(3)],
        #                                             None,
        #                                             [ExitHold("MURAL", ["OBSERVE"], "An ambitous painting of a marketplace. The artist ran out of space on the right.", " If you're being honest it's pretty amateurish.")],
        #                                             [[block_exit], [], {"block_exit" : [1, 0, False]}]
        #                                             ))]}]),
        # Room("MAGIC BRIDGE CHASM", 
        #     "A narrow chasm with a bridge that has a strange aura. This is a placeholder for the room description",
        #     [Exit(0)],
        #     MonsterSpawning(7, FlyingGoblin, 10, "TWICE"),
        #     [Chasm(0, ["JUMP", "CROSS BRIDGE", "TAKE BRIDGE", "THROW ROCKS"], ". You hear them bounce off several different surfaces before coming to rest a significant distance down.", 5, "MAGIC")],
        #     [[], [], {"jump_failure" : [" You cascade off several different rocky outcroppings before finally landing amongst several particularly jagged rocks.", 8],
        #                 "change_room" : [Exit(2, Room("IMMEDIATE RETURN LANDING",
        #                                             "You're in a dark cavern with a deeply uneven surface. You see the chasm continues further down, you were lucky you didn't fall further. Looking upward there's a potential CLIMBING PATH nearby.",
        #                                             [Exit(0)],
        #                                             None,
        #                                             [ExitHold("ROCKY PROTRUSION", [], "A small island of rock that rises out of the water"),
        #                                                 SecretPassage("CHASM EDGE", 0, [], "A rocky wall that might be climbable.", 1, 0, reveal_passage)],
        #                                             [[block_exit], [], {"block_exit": [1, 0, False],
        #                                                                 "reveal_passage" : [" You're able to confirm a CLIMBING PATH! It looks pretty reliable.", "CLIMBING PATH"],
        #                                                                 "change_room" : [0]}]))]}]),
        Room("LOCKED DOOR ROOM 1",
            "Placeholder, there's a locked door on the edge of this room.",
            [Exit(0), Exit(1)],
            MonsterSpawning(7, Goblin),
            [ExitHold("LARGE ROCK", ["SIT"], "A rock that looks good for sitting.", "It's a pretty good spot to sit."),
                LockedDoor(9)],
            [[], [], {"reveal_passage" : [" You unlocked the door!", "OPEN DOOR"],
                        "change_room" : [Exit(2, Room("TREASURE ROOM 1",
                                                        "A room with a bunch of money and a treasure chest!",
                                                        [Exit(0)],
                                                        None,
                                                        [PileOfMoney(1, 20),
                                                            Chest(0, ["BREAK THE LOCK", "USE A KEY"], "A treasure chest", 8, [misc_options["KEY"], misc_options["BOOK OF FAE LANGUAGE"]])]))]}]),
        Room("LOCKED DOOR ROOM 2",
            "Placeholder, there's a locked door on the edge of this room.",
            [Exit(0), Exit(1)],
            MonsterSpawning(7, Goblin),
            [ExitHold("LARGE ROCK", ["SIT"], "A rock that looks good for sitting.", "It actually is kinda uncomfortable"),
                LockedDoor(8)],
            [[], [], {"reveal_passage" : [" You unlocked the door!", "OPEN DOOR"],
                        "change_room" : [Exit(2, Room("TREASURE ROOM 2",
                                                        "A room with a bunch of money and a treasure chest!",
                                                        [Exit(0)],
                                                        None,
                                                        [PileOfMoney(1, 15),
                                                            Chest(0, ["BREAK THE LOCK", "USE A KEY"], "A treasure chest", 8, [misc_options["KEY"], misc_options["SHIELD"]])]))]}]),
        # Room("SMALL MAGMA RIVER", 
        #     "A 10ft wide river of magma flows in your path, blocking the exit opposite from you", 
        #     [Exit(0)], 
        #     MonsterSpawning(5, MagmaGoblin, 10, "TWICE"),
        #     [MagmaRiver(0, ["JUMP", "BUILD BRIDGE", "THROW ROCKS"], "10ft ", Exit(1, Room("SMALL MAGMA RIVER PASSAGE", 
        #                                                                             "A tunnel beyond the magma river opens to a chamber with a chest. The path continues onward.", 
        #                                                                             [Exit(0), Exit(1)], 
        #                                                                             MonsterSpawning(5, Goblin), 
        #                                                                             [Chest(0, ["BREAK THE LOCK", "USE A KEY"]," with an image of a volcano etched onto its top.", 3, [weapon_options["LONGSWORD"], StatMedallion(), 40])])))]),
        # Room("WATER CHASM ROOM",
        #     "A wide chasm with a rickety, old bridge. Below the bridge is a drop into nothingness.",
        #     [Exit(0)],
        #     MonsterSpawning(7, FlyingGoblin, 10, "TWICE"),
        #     [Chasm(0, ["JUMP", "CROSS BRIDGE", "THROW ROCKS"], ", it makes a loud splash.", 5, "RICKETY OLD")],
        #     [[], [], {"wood_failure" : ["A wide chasm with no more rickety old bridges."],
        #                 "jump_failure" : [" You land with smack, as you break the still surface of a body of water.", 2],
        #                 "change_room" : [Exit(2, Room("CHASM SEA CREATURE",
        #                                                 " You quickly swim back up for air. Once you do, you find yourself surrounded in total darkness.",
        #                                                 [Exit(0)],
        #                                                 None,
        #                                                 [ExitHold("ROCKY PROTRUSION", [], "A small island of rock that rises out of the water"),
                                                            # SecretPassage("CHASM EDGE", 0, [], "A rocky wall that might be climbable, if you weren't being held underwater by a SEA CREATURE.", 1, 0, reveal_passage),
        #                                                     Pool(0, "LAKE", [], "It's dark under the surface, you can't see what's below you at all.")],
        #                                                     [[block_exit, chasm_sea_creature_start1], [sea_creature_defeated], {"block_exit": [1, 0, False],
        #                                                                                                                         "reveal_passage" : [" You see a way that you could climb back up the wall!", "CLIMBING PATH"],
        #                                                                                                                         "sea_creature_defeated" : ["You quickly swim back up for air. Once you do, you find yourself surrounded in total darkness.. Again."],
        #                                                                                                                         "damage_player" : ["Your armor is too heavy to swim in!", 2],
        #                                                                                                                         "change_room" : [0]}]))]}]),
        # Room("LAVA MISSISSIPPI", 
        #     "A 20ft wide river of magma flows in your path, blocking the exit opposite from you", 
        #     [Exit(0)], 
        #     MonsterSpawning(5, MagmaGoblin, 10, "TWICE"),
        #     [MagmaRiver(0, ["JUMP", "BUILD BRIDGE", "THROW ROCKS"], "20ft ", Exit(1, Room("LAVA MISSISSIPPI PASSAGE", 
        #                                                                             "A tunnel beyond the lava mississippi opens to a chamber with two chests. The path continues onward.", 
        #                                                                             [Exit(0), Exit(1)], 
        #                                                                             MonsterSpawning(5, Wizard), 
        #                                                                             [Chest(1, ["OPEN"], "", 0, [GreaterHealthPotion, misc_options["MAGIC BRIDGE"], misc_options["SHIELD"], 30]),
        #                                                                                 Chest(2, ["BREAK THE LOCK", "USE A KEY"]," with an image of a volcano etched onto its top.", 7, [weapon_options["BATTLE AXE"], StatMedallion(), 65])])), 8)]),
        # Room("SKELETON FORTRESS ENTRANCE",
        #     "Your path opens and you see a stone brick wall spanning the width of the chamber. The wall has an open portcullis and a lowered drawbridge; over the wall you can see the top of the castle's keep.",
        #     [Exit(0), Exit(1, Room("SKELETON FORTRESS COURTYARD",
        #                             "",
        #                             [Exit(0)],
        #                             None,
        #                             [ExitHold("PORTCULLIS", ["OPEN"], "A vertically-sliding, metal gate that keeps enemies out... or in", "it's too heavy."),
        #                                 SecretPassage("SKELETON FORTRESS KEEP", 0, ["CASTLE DOOR"], "A large keep that served as residence for whoever built this castle, before it found it's way into the dungeon.", 0, 3),
        #                                 RedHerring("STATUE", 0, [], "A statue of a horse with a sword in it's mouth.", 0, 3, "The horse looks bigger than it should.")],
        #                             [[add_monsters, block_exit], [add_castle_wave], {"add_monsters" : [1, 1, Skeleton],
        #                                                                             "block_exit" : [1, 0, f""" As you pass through the portcullis you see a castle courtyard. There is a statue at it's center, a stone keep to your right, and a far wall with a closed portcullis. \n Suddenly the portcullis behind you slams closed, and you see 4 SKELETONS look to your direction!"""],
        #                                                                             "add_castle_wave" : [1],
        #                                                                             "change_room_description": [1, "The courtyard of a castle recently relieved of SKELETONS."],
        #                                                                             "change_room" : [Exit(1, Room("SKELETON KEEP INTERIOR", 
        #                                                                                                             "Wondering through the spacious keep you find a cozy looking bed to rest in, a cauldron, and three treasure chests.",
        #                                                                                                             [Exit(0)],
        #                                                                                                             None,
        #                                                                                                             [Bed(0, "COZY BED", ["REST", "CHOP"], "A large bed with thick fluffy blankets and pillows", 16),
        #                                                                                                                 Cauldron(),
        #                                                                                                                 Chest(1, ["OPEN"], contents=[StatMedallion()]),
        #                                                                                                                 Chest(2, ["OPEN"], contents=[GreaterHealthPotion()]),
        #                                                                                                                 Chest(3, ["BREAK THE LOCK", "USE A KEY"], challenge=7, contents=[65, weapon_options["BATTLE AXE"], misc_options["SHIELD"], misc_options["BOOK OF FAE LANGUAGE"]])],
        #                                                                                                             [[change_room_description], [], {"change_room_description" : [2, "A spacious keep used by the castle's previous owners. Mysteriously the SKELETONS don't seem to have had an impact on it."]}]))]}]))],
        #     adjustments=[[change_room_description, add_interactable], [], {"change_room_description" : [0, "The antechamber to a castle recently relieved of SKELETONS. Some rocks have fallen down along it's edge revealing a SECRET TUNNEL."],
        #                                                                     "add_interactable" : [0, SecretPassage("ROCK SLIDE", 0, ["SECRET TUNNEL"], "An opening in the wall that leads somewhere.", 0, 0)],
        #                                                                     "change_room" : [Exit(2, Room("FAIRY FOUNTAIN",
        #                                                                                                     "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
        #                                                                                                     [Exit(0)],
        #                                                                                                     None,
        #                                                                                                     [Fairy(0, 
        #                                                                                                             "A young-looking, humanlike creature with pointy ears and butterfly wings", 
        #                                                                                                             "WARROW", 
        #                                                                                                             ["she", "her", "hers", "her", "herself"], 
        #                                                                                                             ["Thanks for getting rid of those SKELETONS! They were trash neighbors.", "Heyyyyy wait do you just pick on everybody? Not cool!", "I had hopes for you but not anymore! Leave me alone!", "Yeah I'll buy! Got anything bright?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
        #                                                                                                             6)]))]}]),
        #     Room("WIZARD TOWER ENTRANCE",
        #     "Your path opens and you see a massive tower encircled by green energy and floating rocks. The front gate is littered with glowing runes, and open.",
        #     [Exit(0), Exit(1, Room("WIZARD TOWER LIBRARY",
        #                             "",
        #                             [Exit(0)],
        #                             None,
        #                             [ExitHold("GATE", ["OPEN"], "A metal gate with magical glowing runes that keep enemies out... or in", "it's too heavy."),
        #                                 SecretPassage("WIZARD TOWER UPPER FLOORS", 0, ["STAIRCASE"], "The upper floors of this tower where the original mage studied before the WIZARDS overthrew him.", 0, 3),
        #                                 RedHerring("BOOKSHELVES", 0, [], "A library of knowledge.", 0, 3, "You could spend a lifetime and never finish a third of them.")],
        #                             [[add_monsters, block_exit], [add_castle_wave], {"add_monsters" : [1, 1, Wizard],
        #                                                                             "block_exit" : [1, 0, f""" As you pass through the gate you see 40ft high walls covered in bookcases, each packed with books, pages, notes, and tomes of varying sizes and colors. The smell is musky, and a massive staircase leads to the upper floors. \n Suddenly the gate behind you slams closed, and you see 5 WIZARDS look to your direction!"""],
        #                                                                             "add_castle_wave" : [1],
        #                                                                             "change_room_description": [1, "The entrance hall of a tower relieved of WIZARDS. Bookcases stuffed to the brim with tomes cover every inch of the 40ft-high walls"],
        #                                                                             "change_room" : [Exit(1, Room("WIZARD TOWER SANCTUM", 
        #                                                                                                             "Wondering through the spacious tower you find a cozy looking bed to rest in, a cauldron, and 5 treasure chests.",
        #                                                                                                             [Exit(0)],
        #                                                                                                             None,
        #                                                                                                             [Bed(0, "COZY BED", ["REST", "CHOP"], "A large bed with thick fluffy blankets and pillows", 22),
        #                                                                                                                 Cauldron(),
        #                                                                                                                 Chest(1, ["OPEN"], contents=[StatMedallion()]),
        #                                                                                                                 Chest(2, ["OPEN"], contents=[GreaterHealthPotion()]),
        #                                                                                                                 Chest(3, ["BREAK THE LOCK", "USE A KEY"], challenge=9, contents=[weapon_options["MAGIC SWORD"]]),
        #                                                                                                                 Chest(4, ["BREAK THE LOCK", "USE A KEY"], challenge=9, contents=[armor_options["MAGIC PLATE"]]),
        #                                                                                                                 Chest(5, ["BREAK THE LOCK", "USE A KEY"], challenge=9, contents=[StatMedallion()]),
        #                                                                                                                 ],
        #                                                                                                             [[change_room_description], [], {"change_room_description" : [2, "The upper floors used as a lab and residence by the tower's previous owner. Its hard to tell what damage was caused by the WIZARDS or the original owner."]}]))]}]))],
        #     adjustments=[[change_room_description, add_interactable], [], {"change_room_description" : [0, "The grounds outside a tower recently relieved of WIZARDS. Some rocks have fallen down along it's edge revealing a SECRET TUNNEL."],
        #                                                                     "add_interactable" : [0, SecretPassage("ROCK SLIDE", 0, ["SECRET TUNNEL"], "An opening in the wall that leads somewhere.", 0, 0)],
        #                                                                     "change_room" : [Exit(2, Room("FAIRY FOUNTAIN",
        #                                                                                                     "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
        #                                                                                                     [Exit(0)],
        #                                                                                                     None,
        #                                                                                                     [Fairy(0, 
        #                                                                                                             "A young-looking, humanlike creature with pointy ears and butterfly wings", 
        #                                                                                                             "TARROW", 
        #                                                                                                             ["she", "her", "hers", "her", "herself"], 
        #                                                                                                             ["Wow congrats on defeating all of those WIZARDS! If any adventurer is capable of escaping with the IDOL OF DYNAE, its you!", "Heyyyyy wait do you just pick on everybody? Not cool!", "I had hopes for you but not anymore! Leave me alone!", "Yeah I'll buy! Got anything bright?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
        #                                                                                                             6)]))]}]),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 9, "TWICE")),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)], MonsterSpawning(5, Goblin, 9, Skeleton)),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)], MonsterSpawning(5, Goblin, 9, Skeleton)),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)], MonsterSpawning(5, Goblin, 9, Skeleton)),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)], MonsterSpawning(5, Goblin, 9, Skeleton)),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)]),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)]),
        # Room("Deadend", "Placeholder for a deadend", [Exit(0)]),
        # Room("SECOND FLOOR TUNNEL", 
        #     "A narrow tunnel softly spiraling downward. This is the path to the dungeon's second floor, necessary to finding the idol.", 
        #     [Exit(0), Exit(1, Room("SECOND FLOOR LANDING", 
        #                                 "The entrance chamber to the second floor is built of smooth, blue bricks. Decorative pillars dot the edges, and an archway leads to three exits leading deeper into the dungeon.", 
        #                                 exits=[Exit(0), Exit(1), Exit(2), Exit(3)]))])
        Room("BUFFER ROOM",
            "THIS IS A BUFFER ROOM IT SHOULDN'T BE SEEN IN THE GAME IF IT IS CALL THE FBI",
            [Exit(0)])
        ],
    [
        # Room("GLOWING CRYSTALS ROOM", 
        #     "A room with some glowing crystals.", 
        #     [Exit(0), Exit(1), Exit(2), Exit(3)], 
        #     MonsterSpawning(5, Goblin, 8, Skeleton), 
        #     [GlowingCrystal(1, ["SHATTER", "INSPECT"], " human baby.", challenge=5), 
        #         GlowingCrystal(2, ["SHATTER", "INSPECT"], " chair.", challenge=8), 
        #         GlowingCrystal(3, ["SHATTER", "INSPECT"], "n adult horse.", challenge=11)]),
        # Room("FOUNTAIN ROOM", 
        #     "You come across a large fountain, the white marble gently glowing against the dim light. The water is fairly shallow- maybe three feet deep, and there's a statue nearby of a dwarven lad reading a book.", 
        #     [Exit(0), Exit(1), Exit(2)], 
        #     MonsterSpawning(7, Wizard), 
        #     [Pool(0, "FOUNTAIN", ["SWIM", "THROW ROCKS"], "A mysterious fountain that has an eerie (albeit welcoming) aura."),
        #     Chest(0, ["BREAK THE LOCK", "USE A KEY"], " that looks kinda tough.", challenge=6, contents=[40, StatMedallion(), misc_options["MINOTAUR HORN"]]),
        #     RedHerring(0, "STATUE", ["SIT", "INSPECT"], "A white marble statue that almost has a glow to it. The dwarven lad looks to be in his later years, and sports hardy mutton chops with small glasses.", "The refracted light from the water dances across the statue.")]),
        # Room("ALCHEMIST CONDO",
        #     "You see a door with an 'OPEN 7 DAYS A WEEK' sign on the front. Inside is a homely shop, its counters covered with books, tools, vials, and strange ingredients. You see an incredibly frail old woman hunched over an emerald cauldron.",
        #     [Exit(0)],
        #     None,
        #     [Artisan(0,
        #             ["TALK", "SELL", "HIRE", "ROB"],
        #             "An incredibly frail, old-old woman smiles at you with zero teeth in her face. Surprisingly she smells fine.",
        #             "CERIBANE",
        #             ["she", "her", "hers", "her", "herself"],
        #             ["Let great-grandmother make you a potion.", "These eyes see everything child. Begone!", "(She says something in a fae language that you don't understand.)", "Yes, let great-grandmother see what you've brought for her.", "Thank you for the business child. We won't forget.", "Sweetie you don't have anything to sell me.", "I can brew you a STAT MEDALLION if you can bring me two GOLEM EYEBALLS."],
        #             12,
        #             0,
        #             ceribane_alchemy,
        #             [MagicWand(), misc_options["MINOTAUR HORN"]],
        #             misc_options["GOLEM EYE"],
        #             2),
        #         Cauldron(0, ["COOK"], True)],
        #     [[], [], {"ceribane_alchemy" : [0]}]),
        # Room("CAVE IN",
        #     "A rocky tunnel with heavy timbers reenforcing the walls.",
        #     [Exit(0), Exit(1, Room("EXCAVATOR ROOM",
        #                             "A rocky chamber with heavy timbers reenforcing the walls. A burly woman sits at a table with a plate of food and some drink, nearby a display rack holds various digging and mining tools.",
        #                             [Exit(0), Exit(1), Exit(2), Exit(3)],
        #                             None,
        #                             [Breakable("TABLE", 0, ["SIT", "CHOP"], " A picnic style table.", 0, 2, contents=misc_options["WOOD"]),
        #                                 RedHerring("DISPLAY RACK", 0, ["LICK"], "A metal frame with multiple hooks for hanging tools.", " HARBOR: Please stop licking my tools?"),
        #                                 Artisan(0, 
        #                                         ["TALK", "ROB", "SELL", "HIRE"],
        #                                         "A buff woman in her late 50's. She has short, light brown hair and is covered with sick tattoos.",
        #                                         "HARBOR",
        #                                         ["she", "her", "hers", "her", "herself"],
        #                                         ["That tunnel had another cave in huh? There's something unnatural about it, but that's what I'm here for.", "Hey! You want to start something??", "Beat it, I don't need to deal with you.", "Yeah I'll take a look, what'd'ya have?", "Nice, I appreciate it", "You don't really have anything useful to me.", "I can clear the path if you want but it's gonna cost. Charity doesn't buy much. 20 dollar bills if you're interested."],
        #                                         6,
        #                                         20,
        #                                         clear_cave_in)],
        #                             [[], [break_the_table], {"add_interactable" : [0, None]}]))],
        #     MonsterSpawning(5, Goblin, 8, Skeleton), 
        #     [ExitHold("ROCK PILE", ["INSPECT"], "A pile of rocks blocking your path.", "Unless you can INSPECT your way through a cave in, this isn't going away any time soon."),
        #     ExitHold("TIMBER FRAMES", ["INSPECT"], "Multiple wooden frames meant to support the overhead rocks.", "There seem to be a lot for a tunnel this unremarkable, especially considering they didn't work that well.")],
        #     [[block_exit], [], {"block_exit": [1, 0, " As you enter the tunnel, the room begins shaking heavily. Several large bolders fall behind you, blocking your path back. After a moment the shaking stops."]}]),
        # Room("SMALL POISON GAS ROOM",
        #     "Upon crossing a door you find yourself in a room filled with a green acidic gas. At the far end you see two chests behind a magical barrier. To the right of the barrier is some kind of control panel.",
        #     [Exit(0)],
        #     MonsterSpawning(5, Goblin, 9, Skeleton),
        #     [Inspectable("CONTROL PANEL", 0, ["INSPECT FIRST DIAL"], "A metal panel with two dials, each with different runes along it's rim.", 9, 2, inspect_control_panel)],
        #     [[], [damage_player], {"damage_player" : ["The acidic gas burns your skin.", 1],
        #                             "shutdown_control_panel" : [Chest(1, ["OPEN"], "", 0, [18, GreaterHealthPotion(), SmokeBomb(), weapon_options["MIMIC TOOTH"], StatMedallion()]), 
        #                                                         Chest(2, ["BREAK THE LOCK", "USE A KEY"], "with a lock", 3, [40, StatMedallion(), GreaterHealthPotion(), weapon_options["LONGSWORD"], armor_options["CHAINMAIL"]])]}]),
        # Room("GOBLIN FORTRESS ENTRANCE",
        #     "Your path opens and you see a stone brick wall spanning the width of the chamber. The wall has an open portcullis and a lowered drawbridge; over the wall you can see the top of the castle's keep.",
        #     [Exit(0), Exit(1, Room("GOBLIN FORTRESS COURTYARD",
        #                             "",
        #                             [Exit(0)],
        #                             None,
        #                             [ExitHold("PORTCULLIS", ["OPEN"], "A vertically-sliding, metal gate that keeps enemies out... or in", "it's too heavy."),
        #                                 SecretPassage("GOBLIN FORTRESS KEEP", 0, ["CASTLE DOOR"], "A large keep that served as residence for whoever built this castle, before it found it's way into the dungeon.", 0, 3),
        #                                 RedHerring("STATUE", 0, [], "A statue of a woman with a raised sword on a neighing horse", 0, 3, "It's of an elven woman with a raised sword on a neighing horse. There's a small figure hunched over her lap, and the base is decorated with waves and horses.")],
        #                             [[add_monsters, block_exit], [add_castle_wave], {"add_monsters" : [1, 1, Goblin],
        #                                                                             "block_exit" : [1, 0, f""" As you pass through the portcullis you see a castle courtyard. There is a statue at it's center, a stone keep to your right, and a far wall with a closed portcullis. \n Suddenly the portcullis behind you slams closed, and you see 3 GOBLINS look to your direction!"""],
        #                                                                             "add_castle_wave" : [1],
        #                                                                             "change_room_description": [1, "The courtyard of a castle recently relieved of GOBLINS."],
        #                                                                             "change_room" : [Exit(1, Room("GOBLIN KEEP INTERIOR", 
        #                                                                                                             "Wondering through the spacious keep you find a cozy looking bed to rest in, a cauldron, and three treasure chests.",
        #                                                                                                             [Exit(0)],
        #                                                                                                             None,
        #                                                                                                             [Bed(0, "COZY BED", ["REST", "CHOP"], "A large bed with thick fluffy blankets and pillows", 10),
        #                                                                                                                 Cauldron(),
        #                                                                                                                 Chest(1, ["OPEN"], contents=[StatMedallion()]),
        #                                                                                                                 Chest(2, ["OPEN"], contents=[GreaterHealthPotion()]),
        #                                                                                                                 Chest(3, ["BREAK THE LOCK", "USE A KEY"], challenge=5, contents=[45, weapon_options["LONGSWORD"], misc_options["SHIELD"], misc_options["BOOK OF FAE LANGUAGE"]])],
        #                                                                                                             [[change_room_description], [], {"change_room_description" : [2, "A spacious keep used by the castle's previous owners. Mysteriously the GOBLINS don't seem to have had an impact on it."]}]))]}]))],
        #     adjustments=[[change_room_description, add_interactable], [], {"change_room_description" : [0, "The antechamber to a castle recently relieved of GOBLINS. Some rocks have fallen down along it's edge revealing a SECRET TUNNEL."],
        #                                                                     "add_interactable" : [0, SecretPassage("ROCK SLIDE", 0, ["SECRET TUNNEL"], "An opening in the wall that leads somewhere.", 0, 0)],
        #                                                                     "change_room" : [Exit(2, Room("FAIRY FOUNTAIN",
        #                                                                                                     "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
        #                                                                                                     [Exit(0)],
        #                                                                                                     None,
        #                                                                                                     [Fairy(0, 
        #                                                                                                             "A young-looking, humanlike creature with pointy ears and butterfly wings", 
        #                                                                                                             "HARROW", 
        #                                                                                                             ["she", "her", "hers", "her", "herself"], 
        #                                                                                                             ["Thanks for getting rid of those GOBLINS! They were trash neighbors.", "Heyyyyy wait do you just pick on everybody? Not cool!", "I had hopes for you but not anymore! Leave me alone!", "Yeah I'll buy! Got anything bright?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
        #                                                                                                             6)]))]}]),
            # Room("FAIRY STATUE",
            # "While traveling through a tunnel you come across a short stretch that has a statue along it's edge. The statue shows a humaniod creature with pointed ears and dragonfly wings.",
            # [Exit(0), Exit(1)],
            # MonsterSpawning(6, Goblin),
            # [ExitHold("PLAQUE", ["READ"], "An ornate plaque carved into the wall.", "A statue of KANE, one of the eleven fairies rumored to live in this dungeon."),
            #     SecretPassage("STATUE", 0, ["INSPECT"], "A statue of KANE, one of the nine fairies known to live in this dungeon.", 5, 2, reveal_passage)],
            # [[inspectable_renew], [], {"reveal_passage" : [" The statue slides to the right, revealing a secret tunnel.", "SECRET TUNNEL"],
            #             "change_room" : [Exit(2, Room("FAIRY FOUNTAIN",
            #                                     "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            #                                     [Exit(0)],
            #                                     None,
            #                                     [Fairy(0, 
            #                                             "A young-looking, humanlike creature with pointy ears and dragonfly wings", 
            #                                             "KANE", 
            #                                             ["she", "her", "hers", "her", "herself"], 
            #                                             ["You look silly.", "Are you kidding?? I could eat you, give it back!", "You're a jerk, I don't hang out with jerks. Jerk", "Yeah I'll buy! Got anything stinky?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
            #                                             6),
            #                                     Chest(0, ["OPEN"], "", 0, [15, HealthPotion(), SmokeBomb(), DurabilityGem(), MagicWand()])]))]}]),
        # Room("SKELETON CAMP",
        #     "You see a fire pit illuminating a scattering of small tents. Multiple skeletons meander amongst them, it seems this is their camp.",
        #     [Exit(0), Exit(1), Exit(2), Exit(3)],
        #     MonsterSpawning(100, Skeleton, 200, "TWICE"),
        #     [Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 3),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 3),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 3),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 4),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 3),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 2),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 2),
        #         Breakable("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 2),
        #         Mimic("TENT", 0, ["SMASH"], "A small tent that belongs to some skeleton.", 1, 3)],
        #     [[add_monsters, change_monster_spawning, change_adjustable_argument, randomize_container_contents], [reveal_mimics], {"add_monsters" : [1, 6, Skeleton], 
        #                                                                                                                             "change_monster_spawning" : [2, MonsterSpawning(1, Skeleton, 2, "TWICE")],
        #                                                                                                                             "change_adjustable_argument" : ["add_monsters", 1, 1],
        #                                                                                                                             "randomize_container_contents": [Skeleton(), Skeleton(), Skeleton(), Skeleton(), DurabilityGem(), StatMedallion(), weapon_options["SHORTSWORD"], SmokeBomb(), None]}]),
        # Room("SKELETON SWARM ROOM",
        #     "An open room with a huge stretch towards the exits, it smells of SKELETONS.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(100, Skeleton),
        #     adjustments=[[add_monsters, change_monster_spawning],
        #                 [], 
        #                 {"add_monsters" : [1, 4, Skeleton], "change_monster_spawning" : [2, MonsterSpawning(1, Skeleton, 5, "TWICE")]}]),
        # Room("ENCHANTMENT HOLLOW",
        #     "An illusion covers the entrance to this hollow, though you're allowed to see through it. A thin, bald man wearing a mask is studying a book- which produces a green mist.",
        #     [Exit(0)],
        #     None,
        #     [GlowingTree(1, ["PICK FRUIT", "CHOP"], " glowing dogwood", 1, 15),
        #         Cauldron(),
        #         Artisan(0, 
        #                 ["TALK", "ENCHANT", "SELL", "ROB"],
        #                 "A thin, bald man with a mask over his mouth and nose. He looks late 40's and has a piercing look in is eyes.", 
        #                 "MODERN", 
        #                 ["he", "him", "his", "his", "himself"], 
        #                 ["Have you come for an enchantment? I require a PLATEMAIL armor and no less than 250 dollar bills.", "I could exile you to vile realms if you were worth the breath, begone filth!", "Don't tempt me.", "Yes, what do you have? I can make use of many things.", "May this serve us both well.", "My time is precious, don't ask if you have nothing to sell.", "You want me to ENCHANT your PLATEMAIL and make it MAGIC PLATE for 250 dollar bills?"],
        #                 18,
        #                 250,
        #                 obtain_item,
        #                 [MagicWand(), misc_options["KEY"], misc_options["PAIR OF GOLEM EYES"], misc_options["MINOTAUR HORN"], misc_options["GLOWING FRUIT"], misc_options["RUBY DUST"], misc_options["SEA CREATURE MEAT"]],
        #                 armor_options["PLATEMAIL"],
        #                 1)],
        #     [[], [], {"obtain_item": [armor_options["MAGIC PLATE"], "You hired MODERN to ENCHANT your PLATEMAIL for 250 dollar bills!"],
        #                 "change_room_description": [0, "An illusion covers the entrance to this hollow, though you're allowed to see through it. A thin, bald man wearing a mask is studying a book- which produces a green mist."]}]),
        # Room("WIZARD SWARM ROOM",
        #     "An open room with a huge stretch towards the exits, it smells of WIZARD.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(100, Wizard),
        #     adjustments=[[add_monsters, change_monster_spawning],
        #                 [], 
        #                 {"add_monsters" : [1, 4, Wizard], "change_monster_spawning" : [2, MonsterSpawning(1, Wizard, 8, "TWICE")]}]),
        # Room("MINOTAUR SWARM ROOM",
        #     "An open room with a huge stretch towards the exit, it smells of MINOTAUR.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(100, Minotaur),
        #     adjustments=[[add_monsters, change_monster_spawning],
        #                 [], 
        #                 {"add_monsters" : [1, 2, Minotaur], "change_monster_spawning" : [2, MonsterSpawning(2, Minotaur, 8, "TWICE")]}]),
        # Room("JUNIOR ALCHEMIST",
        #     "A small grove of large red mushrooms, it smells very strongly of cherries. You see a young person has set up a shop here. They have workstations with mixing vials, books, and a sizable cauldron.", 
        #     [Exit(0)],
        #     None,
        #     [ShopOwner(0, 
        #                 ["TALK", "ROB", "BUY", "SELL"], 
        #                 "A junior alchemist, learning the trade.", 
        #                 "CARTER", 
        #                 ["they", "them", "theirs", "their", "themself"], 
        #                 ["I've been studying down here for two years, even starting to get some more advanced stuff.", "Hey you didn't pay for that!", "No, we're done. Get out", "Sure I'll buy! What've you got?", "Thanks! Please come visit again!", "Yeah you don't have anything to sell me.", "The mushrooms make great health potions so I can sell them for cheap!", "Hey you bought out my whole stock, thanks! I'll get working on a new batch soon."], 
        #                 10, 
        #                 [HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion()],
        #                 1),
        #         Cauldron(0, ["COOK"], True)],
        #     [[shop_refresh], [], {"shop_refresh" : [2, [HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion()]]}]),
        # Room("MIMIC HALLWAY",
        #     "Placeholder description for a hallway",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Mimic("CHEST", 0, ["OPEN"], "A treasure chest")],
        #     [[], [reveal_mimics], {}]),
        # Room("MIMIC STORAGE",
        #     "Placeholder description for a storage room",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Mimic("CRATE", 0, ["OPEN"], "A crate for storing supplies", 0, 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2)],
        #     [[randomize_container_contents], [reveal_mimics], {"randomize_container_contents" : [HealthPotion(), misc_options["APPLES"], SmokeBomb(), None, None]}]),
        # Room("MIMIC STORAGE",
        #     "Placeholder description for a storage room",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Mimic("CRATE", 0, ["OPEN"], "A crate for storing supplies", 0, 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2)],
        #     [[randomize_container_contents], [reveal_mimics], {"randomize_container_contents" : [HealthPotion(), misc_options["APPLES"], SmokeBomb(), None, None]}]),
        # Room("STORAGE",
        #     "Placeholder description for a storage room",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2)],
        #     [[randomize_container_contents], [], {"randomize_container_contents" : [HealthPotion(), misc_options["APPLES"], misc_options["WOOD"], None, None]}]),
        # Room("STORAGE",
        #     "Placeholder description for a storage room",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2)],
        #     [[randomize_container_contents], [], {"randomize_container_contents" : [HealthPotion(), misc_options["APPLES"], misc_options["WOOD"], None, None]}]),
        # Room("STORAGE",
        #     "Placeholder description for a storage room",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(7, Goblin),
        #     [Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2),
        #         Container("CRATE", 0, ["OPEN"], "A crate for storing supplies", 2)],
        #     [[randomize_container_contents], [], {"randomize_container_contents" : [HealthPotion(), misc_options["APPLES"], misc_options["WOOD"], None, None]}]),
        # Room("MONEY TREE ROOM",
        #     "A room with a money tree placeholder description lol",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(5, Wizard),
        #     [MoneyTree(["PICK FRUIT", "CHOP"])],
        #     [[money_tree_refresh], [add_owl], {"money_tree_refresh" : [0], "add_owl" : [ Owl()]}]), ####change the number here to 4 post testing
        # Room("HASTILY ABANDOND KITCHEN", 
        #     "This room has a large cauldron suspended over a recently extinguished fire pit", 
        #     [Exit(0), Exit(1), Exit(2)], 
        #     MonsterSpawning(5, Goblin, 8, Skeleton),
        #     [Cauldron(),
        #         Chest(1, ["OPEN"], " without a lock."),
        #         Chest(2, ["BREAK THE LOCK", "USE A KEY"], " that looks kinda tough.", challenge=6, contents=[40, StatMedallion(), misc_options["SHIELD"]]),
        #         Chest(3, ["BREAK THE LOCK", "USE A KEY"], " that looks real tough.", challenge=10, contents=[armor_options["MAGIC PLATE"], weapon_options["BATTLE AXE"]]),
        #         Chest(4, ["BREAK THE LOCK", "USE A KEY"], " it looks pretty weak.", challenge=2, contents=[misc_options["KEY"]])],
        #     [[], [change_room_description], {"change_room_description": [0, "This room has a large cauldron suspended over a recently lit fire."]}]),
        # Room("AUTUMNAL FORREST ROOM", 
        #     "A grove of maple trees, the leaves have changed color for the fall.", 
        #     [Exit(0), Exit(1), Exit(2), Exit(3)], 
        #     MonsterSpawning(5, Goblin, 8, Skeleton),
        #     [Tree(1, ["PICK FRUIT", "CHOP"], " maple"),
        #         Tree(2, ["PICK FRUIT", "CHOP"], " maple"),
        #         Tree(3, ["PICK FRUIT", "CHOP"], " maple"),
        #         Tree(4, ["PICK FRUIT", "CHOP"], " maple"),
        #         Tree(5, ["PICK FRUIT", "CHOP"], " maple"),
        #         Tree(6, ["PICK FRUIT", "CHOP"], " maple")],
        #     [[], [add_owl], {"add_owl" : [ Owl()]}]),
        # Room("MAGIC TREE GROVE",
        #     "A small grove of three glowing birch trees, a sourceless breeze is gently blowing here.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(1, Skeleton, 2, "TWICE"),
        #     [GlowingTree(1, ["PICK FRUIT", "CHOP", "INSPECT"], " glowing birch", challenge=7),
        #         GlowingTree(2, ["PICK FRUIT", "CHOP", "INSPECT"], " glowing birch", challenge=7),
        #         GlowingTree(3, ["CHOP"], " glowing birch sapling", challenge=3)],
        #     [[tree_inspect_renew], [add_owl], {"add_owl" : [Owl()]}]),
        # Room("MEDIUM MAGIC TREE",
        #     "A large chamber with a glowing elm tree, a sourceless breeze is gently blowing here.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(1, Skeleton, 2, "TWICE"),
        #     [GlowingTree(0, ["PICK FRUIT", "CHOP", "INSPECT"], " glowing elm", 5, 10)],
        #     [[tree_inspect_renew], [add_owl], {"add_owl" : [Owl()]}]),
        # Room("GIANT SEQUOIA CHAMBER",
        #     "A massively expansive cavern with a glowing, giant sequoia tree in its center. A sourceless breeze is gentle blowing here.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(4, Minotaur),
        #     [GlowingTree(0, ["PICK FRUIT", "CHOP", "INSPECT"], " glowing giant sequoia", 8, 15)],
        #     [[tree_inspect_renew], [add_owl], {"add_owl" : [Owl()]}]),
        # Room("GOLEM FACTORY",
        #     "A rank smell fills this chamber, along with the humming of machines and whistling of released steam. A large drill digs into the cave bed, feeding mud into a massive machine next to it. Two large green crystals power, the machine as it produces a MUD GOLEM.",
        #     [Exit(0), Exit(1), Exit(2)],
        #     MonsterSpawning(1, MudGolem),
        #     [Inspectable("MACHINE", 0, ["INSPECT"], "A massive achievment of artificery. This machine is making MUD GOLEMS and running nonstop.", 1, 4, inspect_machine),
        #         Breakable("GREEN GEM", 1, ["BREAK"], "A green gemstone 1 foot in diameter.", 3, 2, 9),
        #         Breakable("GREEN GEM", 2, ["BREAK"], "A green gemstone 1 foot in diameter.", 3, 2, 9),
        #         Breakable("DRILL", 0, ["BREAK"], "A drill that feeds mud into the machine.", 3, 2, 14)],
        #     [[], [golem_machinery], {"add_monsters" : [0, 1, MudGolem], "change_monster_spawning": [0, None]}]),
        # Room("BILL'S HOVEL", 
        #     "A small room with a bedroll, an extinguished firepit, and some small trinkets on a raw wood table.", 
        #     [Exit(0), Exit(1), Exit(2)],
        #     None,
        #     [Breakable("TABLE", 0, ["CHOP"], " A short section of a tree trunk being used as a table. You can count 21 rings.", 0, 2, contents=misc_options["WOOD"])],
        #     [[add_interactable, change_room_description], [break_the_table], {"add_interactable" : [3, NPC(0, 
        #                                                                                                     ["TALK", "ROB"], 
        #                                                                                                     " A short, teenage-looking, boy with pointed ears and a shaved head.", 
        #                                                                                                     "BILL", 
        #                                                                                                     ["he", "him", "his", "his", "himself"], 
        #                                                                                                     ["Look it's not much but its quiet and I like it here.", "Hey hey hey that's mine! Get out!", "Get out."], 
        #                                                                                                     6)], 
        #                                                                         "change_room_description" : [3, "A small room with a bedroll, an extinguished firepit, and some small trinkets on a raw wood table. A younger looking kid is hanging out and practicing some wood carving."]}]),
        # Room("STELLA'S TRADE CAMP",   #***UPDATE SHOPS TO RESTOCK MORE SLOWLY
        #     "A canvas tent opened in the front reveals a pleasent interior. Currently empty shelves as a woman in her 60's appears to be packing up.", 
        #     [Exit(0), Exit(1), Exit(2)],
        #     None,
        #     [ShopOwner(0, 
        #                 ["TALK", "ROB", "BUY", "SELL"], 
        #                 "Trader in her 60's. Her black hair is in a high bun, and she's wearing square rimmed glasses.", 
        #                 "STELLA", 
        #                 ["she", "her", "hers", "her", "herself"], 
        #                 ["Hey there friend, let me know if you have any questions about my wares!", "Hey I saw that! Drop it and get out of my shop!", "I'm not doing business with someone who tried to rob me. Scram!", "Ooh what do ya got?", "Pleasure doing buisiness with you!", "Mmm you don't really have anything to sell. Come back later, I'd love to see what you find!", "What's catching your eye?", "Afraid I'm all out of stock friend! I'll get some new items soon!"], 
        #                 10, 
        #                 [misc_options["GLOWING FRUIT"], misc_options["KEY"], misc_options["KEY"], HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), DurabilityGem(), DurabilityGem(), DurabilityGem(), DurabilityGem(), SmokeBomb(), SmokeBomb(), SmokeBomb(), SmokeBomb(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), StatMedallion(), StatMedallion(), armor_options["GAMBESON"], weapon_options["LONGSWORD"]])],
        #     [[shop_refresh], [], {"shop_refresh" : [2, [misc_options["GLOWING FRUIT"], misc_options["KEY"], misc_options["KEY"], HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), DurabilityGem(), DurabilityGem(), DurabilityGem(), DurabilityGem(), SmokeBomb(), SmokeBomb(), SmokeBomb(), SmokeBomb(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), StatMedallion(), StatMedallion(), armor_options["GAMBESON"], weapon_options["LONGSWORD"]], "Good news friend, I just restocked my shop! Let me know if you have any questions.", "Hey there friend, let me know if you have any questions about my wares!"]}]),
        # Room("EARLY GOBLIN SWARM ROOM",
        #     "An open room with a huge stretch towards the exit, it smells of GOBLIN.",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(100, Goblin),
        #     adjustments=[[add_monsters, change_monster_spawning],
        #                 [], 
        #                 {"add_monsters" : [1, 3, Goblin], "change_monster_spawning" : [2, MonsterSpawning(1, Goblin, 3, "TWICE")]}]),
        # Room("GOBLIN SWARM ROOM",
        #     "An open room with a huge stretch towards the exit, it smells of GOBLIN.",
        #     [Exit(0), Exit(1)],
        #     MonsterSpawning(100, Goblin),
        #     adjustments=[[add_monsters, change_monster_spawning],
        #                 [], 
        #                 {"add_monsters" : [1, 7, Goblin], "change_monster_spawning" : [2, MonsterSpawning(1, Goblin, 3, "TWICE")]}]),
        # Room("HALLWAY TO PLATE 1",
        #     "A long brick hallway with faux windows that look out to more bricks.",
        #     [Exit(0), Exit(1, Room("HALLWAY TO PLATE 2",
        #                             "A short hallway of bricks, bound by a metal instead of mortar.",
        #                             [Exit(0), Exit(1, Room("PLATE ROOM",
        #                                                     "A small chamber with a short set of steps leading up to a platform with two chests.",
        #                                                     [Exit(0)],
        #                                                     None,
        #                                                     [Chest(1, ["OPEN"], " with an ornate metal trim.", contents=[armor_options["PLATEMAIL"]]),
        #                                                     Chest(2, ["OPEN"], " that's fairly small and has a good scent.", contents=[GreaterHealthPotion()])]))],
        #                             adjustments=[[adjustment_print, add_monsters], [], {"add_monsters" : [2, 8, Skeleton], "adjustment_print" : [2, " A swarm of skeletons has arrived in this room!"]}]))],
        #     adjustments=[[adjustment_print, add_monsters], [], {"add_monsters" : [2, 8, Skeleton], "adjustment_print" : [2, " A swarm of skeletons has arrived in this room!"]}]),
        # Room("FINAL FLOOR POISON GAS ROOM",
        #     "Upon crossing a door you find yourself in a room filled with a green acidic gas. At the far end you see three chests behind a magical barrier. To the right of the barrier is some kind of control panel.",
        #     [Exit(0)],
        #     MonsterSpawning(5, Goblin, 9, Skeleton),
        #     [Inspectable("CONTROL PANEL", 0, ["INSPECT FIRST DIAL"], "A metal panel with two dials, each with different runes along it's rim.", 14, 2, inspect_control_panel)],
        #     [[], [damage_player], {"damage_player" : ["The acidic gas burns your skin.", 3],
        #                             "shutdown_control_panel" : [Chest(1, ["OPEN"], "", 0, [46, GreaterHealthPotion(), weapon_options["BATTLE AXE"], StatMedallion()]), 
        #                                                         Chest(2, ["BREAK THE LOCK", "USE A KEY"], "with a lock", 5, [67, StatMedallion(), weapon_options["BATTLE AXE"], armor_options["PLATEMAIL"]]),
        #                                                         Chest(3, ["BREAK THE LOCK", "USE A KEY"], "with a lock", 6, [73, StatMedallion(), StatMedallion(), weapon_options["MAGIC SWORD"], armor_options["PLATEMAIL"]]),
        #                                                         ]}]),
        Room("SHIELD'S SMITHY",
            "A bare-bones forge with multiple BATTLE AXES on display. A wooden sign is propped up that reads 'SHIELD'S SMITHY'.",
            [Exit(0), Exit(1), Exit(2), Exit(3)],
            None,
            [Breakable("SIGN", 0, ["OBSERVE", "CHOP"], " A wooden sign for the smithy. It was someone's creative outlet for longer than it should've been.", 0, 1, contents=misc_options["WOOD"]),
                Artisan(0, 
                        ["TALK", "ROB", "SELL", "TRADE"],
                        "A scrawnier-looking elvish fellow, they have well conditioned hair for a blacksmith.",
                        "SHIELD",
                        ["they", "them", "theirs", "their", "themself"],
                        ["Welcome to SHIELD'S SMITHY! I'm Shield, the name was a poor choice...", "Woah woah woah woah woah that's not how this works here!", "Sorry, I just gotta ask you to leave.", "Ooh what're we selling today?", "Ayy thanks for that, I appreciate it!", "Mmmm yeah sorry I don't think you've got much I can buy.", "Most Minotaurs on the final floor use a BATTLE AXE. They're incredibly deadly, which is why I sell them to adventurers! 120 dollar bills for one!"],
                        9,
                        120,
                        obtain_item)],
            [[], [break_the_table], {"obtain_item" : [weapon_options["BATTLE AXE"], "You traded with SHIELD and recieved a BATTLE AXE for 120 dollar bills!"]}]),
        Room("FINAL FLOOR MARKET",   #***UPDATE SHOPS TO RESTOCK MORE SLOWLY
            "An unexpectedly inviting market with a canvas tent, a forge, and a cauldron over an unlit fire.", 
            [Exit(0), Exit(1), Exit(2), Exit(3)],
            interactables=[ShopOwner(0, 
                                    ["TALK", "ROB", "BUY", "SELL"], 
                                    "A tall woman in her 30's. She's wearing PLATEMAIL armor, has multiple scars, and a shaved head with two short horns.", 
                                    "GREEN", 
                                    ["she", "her", "hers", "her", "herself"], 
                                    ["There aren't many safe spaces to sell on the final floor. We decided to share this one.", "I've dealt with worse down here, I'll deal with you too theif!", "Piss off punk, I'm not trading with you.", "Oh definitely, let's see what you're selling!", "Nice working with you!", "Sorry I gotta be picky, and I don't see anything on you I'd want to buy", "Here's the haul for now, see anything you like?", "I don't really have anymore to sell, I'll head out and get some new plunder soon."], 
                                    12, 
                                    [misc_options["KEY"], misc_options["KEY"], misc_options["KEY"], HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), DurabilityGem(), DurabilityGem(), DurabilityGem(), DurabilityGem(), SmokeBomb(), SmokeBomb(), SmokeBomb(), SmokeBomb(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), StatMedallion(), StatMedallion(), StatMedallion(), armor_options["CHAINMAIL"], weapon_options["LONGSWORD"], misc_options["SHIELD"], misc_options["MAGIC BRIDGE"]]),
                            Artisan(0,
                                    ["TALK", "ROB", "HIRE", "SELL"],
                                    "A middle aged man with a silver mustache and pompadour. He's wearing a heavy apron and a muscular physique.",
                                    "RYE",
                                    ["he", "him", "his", "his", "himself"],
                                    ["There's a guy that hangs out on this floor who can enchant armor, I can make you a set of PLATEMAIL if you like.", "C'mon, don't be like that.", "Sorry, I can't trust doing business with you.", "Ah I'm sure you have loads of interesting things, to have made it this far.", "Lovely doing business with you!", "Respectfully, you don't have much I could put to use right now. Come back later, I'm sure you'll find something good down here.", "For you, I could make some PLATEMAIL for 150 dollar bills."],
                                    12,
                                    150,
                                    obtain_item,
                                    [Pie(), Pie(), SmokeBomb(), DurabilityGem(), armor_options["PLATEMAIL"], weapon_options["BATTLE AXE"]]),
                            Cauldron(),
                            Breakable("CHAIR", 0, ["SIT", "CHOP"], "A wood stump by the cauldron, would be good for sitting.", 0, 1, contents=misc_options["WOOD"])],
            adjustments=[[shop_refresh], 
                        [change_room_description], 
                        {"shop_refresh" : [2, [misc_options["KEY"], misc_options["KEY"], misc_options["KEY"], HealthPotion(), HealthPotion(), HealthPotion(), HealthPotion(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), PowerBerry(), DurabilityGem(), DurabilityGem(), DurabilityGem(), DurabilityGem(), SmokeBomb(), SmokeBomb(), SmokeBomb(), SmokeBomb(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), GreaterHealthPotion(), StatMedallion(), StatMedallion(), StatMedallion(), armor_options["CHAINMAIL"], weapon_options["LONGSWORD"], misc_options["SHIELD"], misc_options["MAGIC BRIDGE"]], "Nice timing, I just got back from an excursion. Check out my new wares!",  "Here's the haul for now, see anything you like?"],
                        "obtain_item": [armor_options["PLATEMAIL"], "You hired RYE to make you PLATEMAIL for 150 dollar bills!"],
                        "change_room_description": [0, "An unexpectedly inviting market with a canvas tent, a forge, and a cauldron over an open fire."]}]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and golden wings", 
                    "PYTHON", 
                    ["she", "her", "hers", "her", "herself"], 
                    ["Wow you're like way taller than me.", "Ohh someone have a deathwish?", "You're not getting any magic from me.", "Yeah I'll buy! Got anything chunky?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and red wings", 
                    "MITCH", 
                    ["he", "him", "his", "his", "himself"], 
                    ["Thanks for playing my game! I built this using Python but I'm also skilled with Java, Javascript, PHP, CSS, and I'm learning C# next. I'm passionate about artistic expression, I'm an excellent learner, and I think I'm pretty funny too. I'd love to hear more about open positions at your company, as I'm confident I'd make an excellent addition to your team! Please feel free to reach out to my LinkedIn at linkedin.com/in/mitchellshohet", "Oh man I think you owe me a job now!", "Functionally the Fairy class inherits from the NPC class, which has been programmed to refuse talking to or doing business with you after you've robbed them. That being said, I'm still interested in a potential role with your team assuming you won't do that to me in real life! Remember you can reach out to me on my LinkedIn at linkedin.com/in/mitchellshohet. I look forward to hearing from you soon!", "Yeah I'll buy! Got anything fitting for a future employee at your company?", "Nice!!", "Ah your inventory is empty friend.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass! (Wow I'm such a helpful team player!)", "Sweet!! Where to?", "I look forward to hearing from you sooooooooo-!"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and clear wings", 
                    "RYE", 
                    ["he", "him", "his", "his", "himself"], 
                    ["I don't like your hair, but you smell alright.", "Et tu, Brute?", "You robbed me?? Did you think I'd forget?? Now you want my magic????? No????", "Yeah I'll buy! Got anything hairy?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and diamond wings", 
                    "EVER", 
                    ["they", "them", "theirs", "their", "themself"], 
                    ["I like your hair!", "Respect.", "Nope, I don't need to talk to you anymore.", "Yeah I'll buy! Got anything sticky?", "This looks fun! Thanks!", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass!", "Sweet!! Where to?", "All right, see you later!"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and metal wire wings", 
                    "FEATHER", 
                    ["she", "her", "hers", "her", "herself"], 
                    ["Wow, another adventurer. How original.", "Not that I'm surprised, just disappointed.", "Ugh", "Yeah I'll buy. Got anything of real interest?", "This looks amusing, thanks.", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to. It'll cost you though, 40 dollar bills or 20 blades of grass.", "Ok, where to?", "All right, good luck"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and wings like giant leaves", 
                    "SILVER", 
                    ["she", "her", "hers", "her", "herself"], 
                    ["Wow!!! An adventurer at my fountain??? AHH how exciting!!", "AHHH oh no I've been hustled!! Grrr how dare you (good one that was sneaky)!", "Grrr I'm so mad grrrr grrrr (please come back this has been so fun!)", "OH MY GOSH YES LET ME BUY SOMETHING!!", "Eee! Hehehehe thanks!", "Umm you don't really have anything I can buy. Please come back when you do!", "You want me to teleport you???? Um yes of course I will!! I can send you to a room you've been to! I just need 40 dollar bills or 20 blades of grass!", "YAY!! Where to???", "All right, see you later adventurer!!"],
                    6)]),
        Room("FAIRY FOUNTAIN",
            "A shallow stone fountain with a few inches of standing water. A fairy floats about, as the theme from Zelda plays.",
            [Exit(0)],
            None,
            [Fairy(0, 
                    "A young-looking, humanlike creature with pointy ears and wings like giant flower petals", 
                    "ARUGULA", 
                    ["she", "her", "hers", "her", "herself"], 
                    ["Wouldn't it be fun if we told each other our true names?? That sounds fun you go first!", "Hey you're not supposed to do that!", "That was so mean, either give me your name now or leave.", "Yeah I'll buy! Then we can talk names?", "This looks fun! Ok now who do I make the check out to?", "Nothing you have looks that interesting.", "Sure, I can teleport you to a room you've been to! It'll cost you though, 40 dollar bills or 20 blades of grass! I also have a membership for unlimited teleports if you wanna sign up with a name and phone number?", "Sweet!! Where do you wanna go and what's the name for this order?", "All right, catch you next time!"],
                    6)]),
        Room("Second Floor Test", "Second Floor test Room1", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(6, Wizard, 10, "TWICE")),
        Room("Second Floor Test", "Second Floor test Room2", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(6, Wizard, 9, MudGolem)),
        Room("Second Floor Test", "Second Floor test Room3", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(4, Skeleton, 8, "TWICE")),
        Room("Second Floor Test", "Second Floor test Room4", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(5, Wizard)),
        Room("Second Floor Test", "Second Floor test Room5", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(5, Wizard)),
        Room("Second Floor Test", "Second Floor test Room6", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(5, Wizard)),
        # Room("Second Floor Test", "Second Floor test Room", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(7, MudGolem)),
        # Room("Second Floor Test", "Second Floor test Room", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(5, Wizard)),
        # Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 8, "TWICE")),
        # Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 8, "TWICE")),
        # Room("Hallway", "Placeholder for a hallway", [Exit(0), Exit(1)], MonsterSpawning(5, Goblin, 8, "TWICE")),
        Room("FINAL FLOOR TUNNEL", "An ornate set of smoothly carved, stone, stairs descending downward for a mile. This is the path to the dungeon's final floor, where you can find the idol and the exit.", [Exit(0), Exit(1, (Room("FINAL FLOOR LANDING", "The entrance chamber to the final floor is flooded with knee high, glowing, green, liquid. Wading into the chamber, you see the paths ahead are lined with rows of stone fangs.", [Exit(0), Exit(1), Exit(2), Exit(3)])))]),
        Room("BUFFER ROOM",
            "THIS IS A BUFFER ROOM IT SHOULDN'T BE SEEN IN THE GAME IF IT IS CALL THE FBI")
        ],
    [
        Room("Final Floor Test", "Final Floor test Room1", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(4, Wizard, 8, "TWICE")),
        # Room("Final Floor Test", "Final Floor test Room", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(1, Skeleton, 4, "TWICE"), [], [Skeleton(), Skeleton()]),
        Room("Final Floor Test", "Final Floor test Room3", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(7, Minotaur)),
        Room("Final Floor Test", "Final Floor test Room4", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(7, Minotaur)),
        Room("Final Floor Test", "Final Floor test Room5", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(5, MudGolem, 10, "TWICE")),
        Room("Final Floor Test", "Final Floor test Room6", [Exit(0), Exit(1), Exit(2)], MonsterSpawning(2, MudGolem)),
        Room("BUFFER ROOM",
            "THIS IS A BUFFER ROOM IT SHOULDN'T BE SEEN IN THE GAME IF IT IS CALL THE FBI")
        
        ]

]